schema_version = "1.0.0"

id = "Control_Render_Regions"
version = "1.0.9"
name = "Control Render Regions"
tagline = "Manage renders in region"
maintainer = "nukkio <nukkiogm@gmail.com>"
type = "add-on"
website = "https://extensions.blender.org/add-ons/control-render-regions/"

tags = ["Render", "Pipeline"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
copyright = [
  "2019-2025 nukkio",
]
platforms = ["windows-x64", "macos-arm64", "macos-x64", "linux-x64"]
wheels = [
	"./wheels/pillow-11.0.0-cp311-cp311-win_amd64.whl",
	"./wheels/pillow-11.0.0-cp311-cp311-manylinux_2_28_x86_64.whl",
	"./wheels/pillow-11.0.0-cp311-cp311-macosx_11_0_arm64.whl",
	"./wheels/pillow-11.0.0-cp311-cp311-macosx_10_10_x86_64.whl",
]

[permissions]
files = "Create script to render from terminal and render regions"







